name: Makefile CI

on:
  push:
    branches: [ "testing", "main" ]
  pull_request:
    branches: [ "testing", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Ubuntu setup
        run: /bin/sh -c "$GITHUB_WORKSPACE/.github/workflows/setup-ubuntu.sh"

      - name: configure-plain
        run: /bin/sh configure

      - name: compile-plain
        run: bmake

      - name: install-plain
        run: sudo bmake install

      - name: cleanup-plain
        run: bmake clean

      - name: configure-openrc
        run: /bin/sh configure --enable-openrc

      - name: compile-openrc
        run: bmake

      - name: install-openrc
        run: sudo bmake install

      - name: cleanup-openrc
        run: bmake clean

      - name: configure-systemd
        run: /bin/sh configure --enable-systemd

      - name: compile-systemd
        run: bmake

      - name: install-systemd
        run: sudo bmake install

